CREATE TABLE Contato (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT
);


CREATE TABLE Telefone (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDCONTATO INT,
    NUMERO VARCHAR(16),
    FOREIGN KEY (IDCONTATO) REFERENCES Contato(ID) ON DELETE CASCADE
);
